//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("PMSDataModel", "FK_PMSITEM_MAINITEM", "MAINITEM", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PMS.MAINITEM), "PMSITEM", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PMS.PMSITEM), true)]

#endregion

namespace PMS
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PMSDataEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PMSDataEntities object using the connection string found in the 'PMSDataEntities' section of the application configuration file.
        /// </summary>
        public PMSDataEntities() : base("name=PMSDataEntities", "PMSDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PMSDataEntities object.
        /// </summary>
        public PMSDataEntities(string connectionString) : base(connectionString, "PMSDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PMSDataEntities object.
        /// </summary>
        public PMSDataEntities(EntityConnection connection) : base(connection, "PMSDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MAINITEM> MAINITEMs
        {
            get
            {
                if ((_MAINITEMs == null))
                {
                    _MAINITEMs = base.CreateObjectSet<MAINITEM>("MAINITEMs");
                }
                return _MAINITEMs;
            }
        }
        private ObjectSet<MAINITEM> _MAINITEMs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PMSITEM> PMSITEMs
        {
            get
            {
                if ((_PMSITEMs == null))
                {
                    _PMSITEMs = base.CreateObjectSet<PMSITEM>("PMSITEMs");
                }
                return _PMSITEMs;
            }
        }
        private ObjectSet<PMSITEM> _PMSITEMs;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MAINITEMs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMAINITEMs(MAINITEM mAINITEM)
        {
            base.AddObject("MAINITEMs", mAINITEM);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PMSITEMs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPMSITEMs(PMSITEM pMSITEM)
        {
            base.AddObject("PMSITEMs", pMSITEM);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PMSDataModel", Name="MAINITEM")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MAINITEM : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MAINITEM object.
        /// </summary>
        /// <param name="mAINCODE">Initial value of the MAINCODE property.</param>
        public static MAINITEM CreateMAINITEM(global::System.Int32 mAINCODE)
        {
            MAINITEM mAINITEM = new MAINITEM();
            mAINITEM.MAINCODE = mAINCODE;
            return mAINITEM;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MAINCODE
        {
            get
            {
                return _MAINCODE;
            }
            set
            {
                if (_MAINCODE != value)
                {
                    OnMAINCODEChanging(value);
                    ReportPropertyChanging("MAINCODE");
                    _MAINCODE = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MAINCODE");
                    OnMAINCODEChanged();
                }
            }
        }
        private global::System.Int32 _MAINCODE;
        partial void OnMAINCODEChanging(global::System.Int32 value);
        partial void OnMAINCODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MAINITEM1
        {
            get
            {
                return _MAINITEM1;
            }
            set
            {
                OnMAINITEM1Changing(value);
                ReportPropertyChanging("MAINITEM1");
                _MAINITEM1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MAINITEM1");
                OnMAINITEM1Changed();
            }
        }
        private global::System.String _MAINITEM1;
        partial void OnMAINITEM1Changing(global::System.String value);
        partial void OnMAINITEM1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SURVTYPE
        {
            get
            {
                return _SURVTYPE;
            }
            set
            {
                OnSURVTYPEChanging(value);
                ReportPropertyChanging("SURVTYPE");
                _SURVTYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SURVTYPE");
                OnSURVTYPEChanged();
            }
        }
        private global::System.String _SURVTYPE;
        partial void OnSURVTYPEChanging(global::System.String value);
        partial void OnSURVTYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String M_P
        {
            get
            {
                return _M_P;
            }
            set
            {
                OnM_PChanging(value);
                ReportPropertyChanging("M_P");
                _M_P = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("M_P");
                OnM_PChanged();
            }
        }
        private global::System.String _M_P;
        partial void OnM_PChanging(global::System.String value);
        partial void OnM_PChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TOTHRS
        {
            get
            {
                return _TOTHRS;
            }
            set
            {
                OnTOTHRSChanging(value);
                ReportPropertyChanging("TOTHRS");
                _TOTHRS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TOTHRS");
                OnTOTHRSChanged();
            }
        }
        private Nullable<global::System.Decimal> _TOTHRS;
        partial void OnTOTHRSChanging(Nullable<global::System.Decimal> value);
        partial void OnTOTHRSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ME
        {
            get
            {
                return _ME;
            }
            set
            {
                OnMEChanging(value);
                ReportPropertyChanging("ME");
                _ME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ME");
                OnMEChanged();
            }
        }
        private Nullable<global::System.Boolean> _ME;
        partial void OnMEChanging(Nullable<global::System.Boolean> value);
        partial void OnMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ORGDIA
        {
            get
            {
                return _ORGDIA;
            }
            set
            {
                OnORGDIAChanging(value);
                ReportPropertyChanging("ORGDIA");
                _ORGDIA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ORGDIA");
                OnORGDIAChanged();
            }
        }
        private Nullable<global::System.Decimal> _ORGDIA;
        partial void OnORGDIAChanging(Nullable<global::System.Decimal> value);
        partial void OnORGDIAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AE
        {
            get
            {
                return _AE;
            }
            set
            {
                OnAEChanging(value);
                ReportPropertyChanging("AE");
                _AE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AE");
                OnAEChanged();
            }
        }
        private Nullable<global::System.Boolean> _AE;
        partial void OnAEChanging(Nullable<global::System.Boolean> value);
        partial void OnAEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> NUM
        {
            get
            {
                return _NUM;
            }
            set
            {
                OnNUMChanging(value);
                ReportPropertyChanging("NUM");
                _NUM = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NUM");
                OnNUMChanged();
            }
        }
        private Nullable<global::System.Decimal> _NUM;
        partial void OnNUMChanging(Nullable<global::System.Decimal> value);
        partial void OnNUMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> THU_DATE
        {
            get
            {
                return _THU_DATE;
            }
            set
            {
                OnTHU_DATEChanging(value);
                ReportPropertyChanging("THU_DATE");
                _THU_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("THU_DATE");
                OnTHU_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _THU_DATE;
        partial void OnTHU_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnTHU_DATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> SEPA
        {
            get
            {
                return _SEPA;
            }
            set
            {
                OnSEPAChanging(value);
                ReportPropertyChanging("SEPA");
                _SEPA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SEPA");
                OnSEPAChanged();
            }
        }
        private Nullable<global::System.Boolean> _SEPA;
        partial void OnSEPAChanging(Nullable<global::System.Boolean> value);
        partial void OnSEPAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ACOMP
        {
            get
            {
                return _ACOMP;
            }
            set
            {
                OnACOMPChanging(value);
                ReportPropertyChanging("ACOMP");
                _ACOMP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ACOMP");
                OnACOMPChanged();
            }
        }
        private Nullable<global::System.Boolean> _ACOMP;
        partial void OnACOMPChanging(Nullable<global::System.Boolean> value);
        partial void OnACOMPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AL
        {
            get
            {
                return _AL;
            }
            set
            {
                OnALChanging(value);
                ReportPropertyChanging("AL");
                _AL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AL");
                OnALChanged();
            }
        }
        private Nullable<global::System.Boolean> _AL;
        partial void OnALChanging(Nullable<global::System.Boolean> value);
        partial void OnALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> PMPOHL
        {
            get
            {
                return _PMPOHL;
            }
            set
            {
                OnPMPOHLChanging(value);
                ReportPropertyChanging("PMPOHL");
                _PMPOHL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PMPOHL");
                OnPMPOHLChanged();
            }
        }
        private Nullable<global::System.Boolean> _PMPOHL;
        partial void OnPMPOHLChanging(Nullable<global::System.Boolean> value);
        partial void OnPMPOHLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> PMPRTN
        {
            get
            {
                return _PMPRTN;
            }
            set
            {
                OnPMPRTNChanging(value);
                ReportPropertyChanging("PMPRTN");
                _PMPRTN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PMPRTN");
                OnPMPRTNChanged();
            }
        }
        private Nullable<global::System.Boolean> _PMPRTN;
        partial void OnPMPRTNChanging(Nullable<global::System.Boolean> value);
        partial void OnPMPRTNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> MOTOHL
        {
            get
            {
                return _MOTOHL;
            }
            set
            {
                OnMOTOHLChanging(value);
                ReportPropertyChanging("MOTOHL");
                _MOTOHL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MOTOHL");
                OnMOTOHLChanged();
            }
        }
        private Nullable<global::System.Boolean> _MOTOHL;
        partial void OnMOTOHLChanging(Nullable<global::System.Boolean> value);
        partial void OnMOTOHLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> MOTRTN
        {
            get
            {
                return _MOTRTN;
            }
            set
            {
                OnMOTRTNChanging(value);
                ReportPropertyChanging("MOTRTN");
                _MOTRTN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MOTRTN");
                OnMOTRTNChanged();
            }
        }
        private Nullable<global::System.Boolean> _MOTRTN;
        partial void OnMOTRTNChanging(Nullable<global::System.Boolean> value);
        partial void OnMOTRTNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> EDITED
        {
            get
            {
                return _EDITED;
            }
            set
            {
                OnEDITEDChanging(value);
                ReportPropertyChanging("EDITED");
                _EDITED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EDITED");
                OnEDITEDChanged();
            }
        }
        private Nullable<global::System.Boolean> _EDITED;
        partial void OnEDITEDChanging(Nullable<global::System.Boolean> value);
        partial void OnEDITEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> L_MGROUP
        {
            get
            {
                return _L_MGROUP;
            }
            set
            {
                OnL_MGROUPChanging(value);
                ReportPropertyChanging("L_MGROUP");
                _L_MGROUP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("L_MGROUP");
                OnL_MGROUPChanged();
            }
        }
        private Nullable<global::System.Boolean> _L_MGROUP;
        partial void OnL_MGROUPChanging(Nullable<global::System.Boolean> value);
        partial void OnL_MGROUPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MTCODE
        {
            get
            {
                return _MTCODE;
            }
            set
            {
                OnMTCODEChanging(value);
                ReportPropertyChanging("MTCODE");
                _MTCODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MTCODE");
                OnMTCODEChanged();
            }
        }
        private global::System.String _MTCODE;
        partial void OnMTCODEChanging(global::System.String value);
        partial void OnMTCODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EDITDT
        {
            get
            {
                return _EDITDT;
            }
            set
            {
                OnEDITDTChanging(value);
                ReportPropertyChanging("EDITDT");
                _EDITDT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EDITDT");
                OnEDITDTChanged();
            }
        }
        private Nullable<global::System.DateTime> _EDITDT;
        partial void OnEDITDTChanging(Nullable<global::System.DateTime> value);
        partial void OnEDITDTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> MES
        {
            get
            {
                return _MES;
            }
            set
            {
                OnMESChanging(value);
                ReportPropertyChanging("MES");
                _MES = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MES");
                OnMESChanged();
            }
        }
        private Nullable<global::System.Boolean> _MES;
        partial void OnMESChanging(Nullable<global::System.Boolean> value);
        partial void OnMESChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GRPMCODE
        {
            get
            {
                return _GRPMCODE;
            }
            set
            {
                OnGRPMCODEChanging(value);
                ReportPropertyChanging("GRPMCODE");
                _GRPMCODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GRPMCODE");
                OnGRPMCODEChanged();
            }
        }
        private global::System.String _GRPMCODE;
        partial void OnGRPMCODEChanging(global::System.String value);
        partial void OnGRPMCODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> OFFUPDT
        {
            get
            {
                return _OFFUPDT;
            }
            set
            {
                OnOFFUPDTChanging(value);
                ReportPropertyChanging("OFFUPDT");
                _OFFUPDT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OFFUPDT");
                OnOFFUPDTChanged();
            }
        }
        private Nullable<global::System.Boolean> _OFFUPDT;
        partial void OnOFFUPDTChanging(Nullable<global::System.Boolean> value);
        partial void OnOFFUPDTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> SLF
        {
            get
            {
                return _SLF;
            }
            set
            {
                OnSLFChanging(value);
                ReportPropertyChanging("SLF");
                _SLF = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SLF");
                OnSLFChanged();
            }
        }
        private Nullable<global::System.Boolean> _SLF;
        partial void OnSLFChanging(Nullable<global::System.Boolean> value);
        partial void OnSLFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BKDT
        {
            get
            {
                return _BKDT;
            }
            set
            {
                OnBKDTChanging(value);
                ReportPropertyChanging("BKDT");
                _BKDT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BKDT");
                OnBKDTChanged();
            }
        }
        private Nullable<global::System.DateTime> _BKDT;
        partial void OnBKDTChanging(Nullable<global::System.DateTime> value);
        partial void OnBKDTChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PMSDataModel", "FK_PMSITEM_MAINITEM", "PMSITEM")]
        public EntityCollection<PMSITEM> PMSITEMs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PMSITEM>("PMSDataModel.FK_PMSITEM_MAINITEM", "PMSITEM");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PMSITEM>("PMSDataModel.FK_PMSITEM_MAINITEM", "PMSITEM", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PMSDataModel", Name="PMSITEM")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PMSITEM : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PMSITEM object.
        /// </summary>
        /// <param name="pMSCODE">Initial value of the PMSCODE property.</param>
        public static PMSITEM CreatePMSITEM(global::System.Int32 pMSCODE)
        {
            PMSITEM pMSITEM = new PMSITEM();
            pMSITEM.PMSCODE = pMSCODE;
            return pMSITEM;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MAINCODE
        {
            get
            {
                return _MAINCODE;
            }
            set
            {
                OnMAINCODEChanging(value);
                ReportPropertyChanging("MAINCODE");
                _MAINCODE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MAINCODE");
                OnMAINCODEChanged();
            }
        }
        private Nullable<global::System.Int32> _MAINCODE;
        partial void OnMAINCODEChanging(Nullable<global::System.Int32> value);
        partial void OnMAINCODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PMSCODE
        {
            get
            {
                return _PMSCODE;
            }
            set
            {
                if (_PMSCODE != value)
                {
                    OnPMSCODEChanging(value);
                    ReportPropertyChanging("PMSCODE");
                    _PMSCODE = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PMSCODE");
                    OnPMSCODEChanged();
                }
            }
        }
        private global::System.Int32 _PMSCODE;
        partial void OnPMSCODEChanging(global::System.Int32 value);
        partial void OnPMSCODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PMSITEM1
        {
            get
            {
                return _PMSITEM1;
            }
            set
            {
                OnPMSITEM1Changing(value);
                ReportPropertyChanging("PMSITEM1");
                _PMSITEM1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PMSITEM1");
                OnPMSITEM1Changed();
            }
        }
        private global::System.String _PMSITEM1;
        partial void OnPMSITEM1Changing(global::System.String value);
        partial void OnPMSITEM1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HEADR
        {
            get
            {
                return _HEADR;
            }
            set
            {
                OnHEADRChanging(value);
                ReportPropertyChanging("HEADR");
                _HEADR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HEADR");
                OnHEADRChanged();
            }
        }
        private global::System.String _HEADR;
        partial void OnHEADRChanging(global::System.String value);
        partial void OnHEADRChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EQCODE
        {
            get
            {
                return _EQCODE;
            }
            set
            {
                OnEQCODEChanging(value);
                ReportPropertyChanging("EQCODE");
                _EQCODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EQCODE");
                OnEQCODEChanged();
            }
        }
        private global::System.String _EQCODE;
        partial void OnEQCODEChanging(global::System.String value);
        partial void OnEQCODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PERIOD
        {
            get
            {
                return _PERIOD;
            }
            set
            {
                OnPERIODChanging(value);
                ReportPropertyChanging("PERIOD");
                _PERIOD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PERIOD");
                OnPERIODChanged();
            }
        }
        private global::System.String _PERIOD;
        partial void OnPERIODChanging(global::System.String value);
        partial void OnPERIODChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> INTERVAL
        {
            get
            {
                return _INTERVAL;
            }
            set
            {
                OnINTERVALChanging(value);
                ReportPropertyChanging("INTERVAL");
                _INTERVAL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("INTERVAL");
                OnINTERVALChanged();
            }
        }
        private Nullable<global::System.Decimal> _INTERVAL;
        partial void OnINTERVALChanging(Nullable<global::System.Decimal> value);
        partial void OnINTERVALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> SCHED
        {
            get
            {
                return _SCHED;
            }
            set
            {
                OnSCHEDChanging(value);
                ReportPropertyChanging("SCHED");
                _SCHED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SCHED");
                OnSCHEDChanged();
            }
        }
        private Nullable<global::System.Decimal> _SCHED;
        partial void OnSCHEDChanging(Nullable<global::System.Decimal> value);
        partial void OnSCHEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> OHAULAT
        {
            get
            {
                return _OHAULAT;
            }
            set
            {
                OnOHAULATChanging(value);
                ReportPropertyChanging("OHAULAT");
                _OHAULAT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OHAULAT");
                OnOHAULATChanged();
            }
        }
        private Nullable<global::System.Decimal> _OHAULAT;
        partial void OnOHAULATChanging(Nullable<global::System.Decimal> value);
        partial void OnOHAULATChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> HRSNET
        {
            get
            {
                return _HRSNET;
            }
            set
            {
                OnHRSNETChanging(value);
                ReportPropertyChanging("HRSNET");
                _HRSNET = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HRSNET");
                OnHRSNETChanged();
            }
        }
        private Nullable<global::System.Decimal> _HRSNET;
        partial void OnHRSNETChanging(Nullable<global::System.Decimal> value);
        partial void OnHRSNETChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String M_E_D
        {
            get
            {
                return _M_E_D;
            }
            set
            {
                OnM_E_DChanging(value);
                ReportPropertyChanging("M_E_D");
                _M_E_D = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("M_E_D");
                OnM_E_DChanged();
            }
        }
        private global::System.String _M_E_D;
        partial void OnM_E_DChanging(global::System.String value);
        partial void OnM_E_DChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> CRIT
        {
            get
            {
                return _CRIT;
            }
            set
            {
                OnCRITChanging(value);
                ReportPropertyChanging("CRIT");
                _CRIT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CRIT");
                OnCRITChanged();
            }
        }
        private Nullable<global::System.Boolean> _CRIT;
        partial void OnCRITChanging(Nullable<global::System.Boolean> value);
        partial void OnCRITChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DATE
        {
            get
            {
                return _DATE;
            }
            set
            {
                OnDATEChanging(value);
                ReportPropertyChanging("DATE");
                _DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATE");
                OnDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _DATE;
        partial void OnDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnDATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> L_DCARB
        {
            get
            {
                return _L_DCARB;
            }
            set
            {
                OnL_DCARBChanging(value);
                ReportPropertyChanging("L_DCARB");
                _L_DCARB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("L_DCARB");
                OnL_DCARBChanged();
            }
        }
        private Nullable<global::System.Boolean> _L_DCARB;
        partial void OnL_DCARBChanging(Nullable<global::System.Boolean> value);
        partial void OnL_DCARBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TYPECODE
        {
            get
            {
                return _TYPECODE;
            }
            set
            {
                OnTYPECODEChanging(value);
                ReportPropertyChanging("TYPECODE");
                _TYPECODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TYPECODE");
                OnTYPECODEChanged();
            }
        }
        private global::System.String _TYPECODE;
        partial void OnTYPECODEChanging(global::System.String value);
        partial void OnTYPECODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> NUM
        {
            get
            {
                return _NUM;
            }
            set
            {
                OnNUMChanging(value);
                ReportPropertyChanging("NUM");
                _NUM = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NUM");
                OnNUMChanged();
            }
        }
        private Nullable<global::System.Decimal> _NUM;
        partial void OnNUMChanging(Nullable<global::System.Decimal> value);
        partial void OnNUMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> STPOINT
        {
            get
            {
                return _STPOINT;
            }
            set
            {
                OnSTPOINTChanging(value);
                ReportPropertyChanging("STPOINT");
                _STPOINT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("STPOINT");
                OnSTPOINTChanged();
            }
        }
        private Nullable<global::System.Decimal> _STPOINT;
        partial void OnSTPOINTChanging(Nullable<global::System.Decimal> value);
        partial void OnSTPOINTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> STPOINT1
        {
            get
            {
                return _STPOINT1;
            }
            set
            {
                OnSTPOINT1Changing(value);
                ReportPropertyChanging("STPOINT1");
                _STPOINT1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("STPOINT1");
                OnSTPOINT1Changed();
            }
        }
        private Nullable<global::System.Decimal> _STPOINT1;
        partial void OnSTPOINT1Changing(Nullable<global::System.Decimal> value);
        partial void OnSTPOINT1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UNITS
        {
            get
            {
                return _UNITS;
            }
            set
            {
                OnUNITSChanging(value);
                ReportPropertyChanging("UNITS");
                _UNITS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UNITS");
                OnUNITSChanged();
            }
        }
        private global::System.String _UNITS;
        partial void OnUNITSChanging(global::System.String value);
        partial void OnUNITSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String E_D_S
        {
            get
            {
                return _E_D_S;
            }
            set
            {
                OnE_D_SChanging(value);
                ReportPropertyChanging("E_D_S");
                _E_D_S = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("E_D_S");
                OnE_D_SChanged();
            }
        }
        private global::System.String _E_D_S;
        partial void OnE_D_SChanging(global::System.String value);
        partial void OnE_D_SChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> EDITED
        {
            get
            {
                return _EDITED;
            }
            set
            {
                OnEDITEDChanging(value);
                ReportPropertyChanging("EDITED");
                _EDITED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EDITED");
                OnEDITEDChanged();
            }
        }
        private Nullable<global::System.Boolean> _EDITED;
        partial void OnEDITEDChanging(Nullable<global::System.Boolean> value);
        partial void OnEDITEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USERS
        {
            get
            {
                return _USERS;
            }
            set
            {
                OnUSERSChanging(value);
                ReportPropertyChanging("USERS");
                _USERS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USERS");
                OnUSERSChanged();
            }
        }
        private global::System.String _USERS;
        partial void OnUSERSChanging(global::System.String value);
        partial void OnUSERSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String REASON
        {
            get
            {
                return _REASON;
            }
            set
            {
                OnREASONChanging(value);
                ReportPropertyChanging("REASON");
                _REASON = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("REASON");
                OnREASONChanged();
            }
        }
        private global::System.String _REASON;
        partial void OnREASONChanging(global::System.String value);
        partial void OnREASONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PTOTHRS
        {
            get
            {
                return _PTOTHRS;
            }
            set
            {
                OnPTOTHRSChanging(value);
                ReportPropertyChanging("PTOTHRS");
                _PTOTHRS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PTOTHRS");
                OnPTOTHRSChanged();
            }
        }
        private Nullable<global::System.Decimal> _PTOTHRS;
        partial void OnPTOTHRSChanging(Nullable<global::System.Decimal> value);
        partial void OnPTOTHRSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> L_PGROUP
        {
            get
            {
                return _L_PGROUP;
            }
            set
            {
                OnL_PGROUPChanging(value);
                ReportPropertyChanging("L_PGROUP");
                _L_PGROUP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("L_PGROUP");
                OnL_PGROUPChanged();
            }
        }
        private Nullable<global::System.Boolean> _L_PGROUP;
        partial void OnL_PGROUPChanging(Nullable<global::System.Boolean> value);
        partial void OnL_PGROUPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> L_PSTPND
        {
            get
            {
                return _L_PSTPND;
            }
            set
            {
                OnL_PSTPNDChanging(value);
                ReportPropertyChanging("L_PSTPND");
                _L_PSTPND = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("L_PSTPND");
                OnL_PSTPNDChanged();
            }
        }
        private Nullable<global::System.Boolean> _L_PSTPND;
        partial void OnL_PSTPNDChanging(Nullable<global::System.Boolean> value);
        partial void OnL_PSTPNDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DTPSTPND
        {
            get
            {
                return _DTPSTPND;
            }
            set
            {
                OnDTPSTPNDChanging(value);
                ReportPropertyChanging("DTPSTPND");
                _DTPSTPND = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DTPSTPND");
                OnDTPSTPNDChanged();
            }
        }
        private Nullable<global::System.DateTime> _DTPSTPND;
        partial void OnDTPSTPNDChanging(Nullable<global::System.DateTime> value);
        partial void OnDTPSTPNDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> NPSTPND
        {
            get
            {
                return _NPSTPND;
            }
            set
            {
                OnNPSTPNDChanging(value);
                ReportPropertyChanging("NPSTPND");
                _NPSTPND = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NPSTPND");
                OnNPSTPNDChanged();
            }
        }
        private Nullable<global::System.Decimal> _NPSTPND;
        partial void OnNPSTPNDChanging(Nullable<global::System.Decimal> value);
        partial void OnNPSTPNDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UPSTPND
        {
            get
            {
                return _UPSTPND;
            }
            set
            {
                OnUPSTPNDChanging(value);
                ReportPropertyChanging("UPSTPND");
                _UPSTPND = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UPSTPND");
                OnUPSTPNDChanged();
            }
        }
        private global::System.String _UPSTPND;
        partial void OnUPSTPNDChanging(global::System.String value);
        partial void OnUPSTPNDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> EO_ECO
        {
            get
            {
                return _EO_ECO;
            }
            set
            {
                OnEO_ECOChanging(value);
                ReportPropertyChanging("EO_ECO");
                _EO_ECO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EO_ECO");
                OnEO_ECOChanged();
            }
        }
        private Nullable<global::System.Boolean> _EO_ECO;
        partial void OnEO_ECOChanging(Nullable<global::System.Boolean> value);
        partial void OnEO_ECOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EDITDT
        {
            get
            {
                return _EDITDT;
            }
            set
            {
                OnEDITDTChanging(value);
                ReportPropertyChanging("EDITDT");
                _EDITDT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EDITDT");
                OnEDITDTChanged();
            }
        }
        private Nullable<global::System.DateTime> _EDITDT;
        partial void OnEDITDTChanging(Nullable<global::System.DateTime> value);
        partial void OnEDITDTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RESPONSE
        {
            get
            {
                return _RESPONSE;
            }
            set
            {
                OnRESPONSEChanging(value);
                ReportPropertyChanging("RESPONSE");
                _RESPONSE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RESPONSE");
                OnRESPONSEChanged();
            }
        }
        private global::System.String _RESPONSE;
        partial void OnRESPONSEChanging(global::System.String value);
        partial void OnRESPONSEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COMMENT
        {
            get
            {
                return _COMMENT;
            }
            set
            {
                OnCOMMENTChanging(value);
                ReportPropertyChanging("COMMENT");
                _COMMENT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COMMENT");
                OnCOMMENTChanged();
            }
        }
        private global::System.String _COMMENT;
        partial void OnCOMMENTChanging(global::System.String value);
        partial void OnCOMMENTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> WARNPRD
        {
            get
            {
                return _WARNPRD;
            }
            set
            {
                OnWARNPRDChanging(value);
                ReportPropertyChanging("WARNPRD");
                _WARNPRD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WARNPRD");
                OnWARNPRDChanged();
            }
        }
        private Nullable<global::System.Decimal> _WARNPRD;
        partial void OnWARNPRDChanging(Nullable<global::System.Decimal> value);
        partial void OnWARNPRDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MANUFCODE
        {
            get
            {
                return _MANUFCODE;
            }
            set
            {
                OnMANUFCODEChanging(value);
                ReportPropertyChanging("MANUFCODE");
                _MANUFCODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MANUFCODE");
                OnMANUFCODEChanged();
            }
        }
        private global::System.String _MANUFCODE;
        partial void OnMANUFCODEChanging(global::System.String value);
        partial void OnMANUFCODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TYPE
        {
            get
            {
                return _TYPE;
            }
            set
            {
                OnTYPEChanging(value);
                ReportPropertyChanging("TYPE");
                _TYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TYPE");
                OnTYPEChanged();
            }
        }
        private global::System.String _TYPE;
        partial void OnTYPEChanging(global::System.String value);
        partial void OnTYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SERIAL
        {
            get
            {
                return _SERIAL;
            }
            set
            {
                OnSERIALChanging(value);
                ReportPropertyChanging("SERIAL");
                _SERIAL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SERIAL");
                OnSERIALChanged();
            }
        }
        private global::System.String _SERIAL;
        partial void OnSERIALChanging(global::System.String value);
        partial void OnSERIALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> DECOMM
        {
            get
            {
                return _DECOMM;
            }
            set
            {
                OnDECOMMChanging(value);
                ReportPropertyChanging("DECOMM");
                _DECOMM = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DECOMM");
                OnDECOMMChanged();
            }
        }
        private Nullable<global::System.Boolean> _DECOMM;
        partial void OnDECOMMChanging(Nullable<global::System.Boolean> value);
        partial void OnDECOMMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String POSTPNDBY
        {
            get
            {
                return _POSTPNDBY;
            }
            set
            {
                OnPOSTPNDBYChanging(value);
                ReportPropertyChanging("POSTPNDBY");
                _POSTPNDBY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("POSTPNDBY");
                OnPOSTPNDBYChanged();
            }
        }
        private global::System.String _POSTPNDBY;
        partial void OnPOSTPNDBYChanging(global::System.String value);
        partial void OnPOSTPNDBYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> STPOINT2
        {
            get
            {
                return _STPOINT2;
            }
            set
            {
                OnSTPOINT2Changing(value);
                ReportPropertyChanging("STPOINT2");
                _STPOINT2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("STPOINT2");
                OnSTPOINT2Changed();
            }
        }
        private Nullable<global::System.Decimal> _STPOINT2;
        partial void OnSTPOINT2Changing(Nullable<global::System.Decimal> value);
        partial void OnSTPOINT2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> STPOINT3
        {
            get
            {
                return _STPOINT3;
            }
            set
            {
                OnSTPOINT3Changing(value);
                ReportPropertyChanging("STPOINT3");
                _STPOINT3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("STPOINT3");
                OnSTPOINT3Changed();
            }
        }
        private Nullable<global::System.Decimal> _STPOINT3;
        partial void OnSTPOINT3Changing(Nullable<global::System.Decimal> value);
        partial void OnSTPOINT3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> STPOINT4
        {
            get
            {
                return _STPOINT4;
            }
            set
            {
                OnSTPOINT4Changing(value);
                ReportPropertyChanging("STPOINT4");
                _STPOINT4 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("STPOINT4");
                OnSTPOINT4Changed();
            }
        }
        private Nullable<global::System.Decimal> _STPOINT4;
        partial void OnSTPOINT4Changing(Nullable<global::System.Decimal> value);
        partial void OnSTPOINT4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SETRANGE
        {
            get
            {
                return _SETRANGE;
            }
            set
            {
                OnSETRANGEChanging(value);
                ReportPropertyChanging("SETRANGE");
                _SETRANGE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SETRANGE");
                OnSETRANGEChanged();
            }
        }
        private global::System.String _SETRANGE;
        partial void OnSETRANGEChanging(global::System.String value);
        partial void OnSETRANGEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> OFFUPDT
        {
            get
            {
                return _OFFUPDT;
            }
            set
            {
                OnOFFUPDTChanging(value);
                ReportPropertyChanging("OFFUPDT");
                _OFFUPDT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OFFUPDT");
                OnOFFUPDTChanged();
            }
        }
        private Nullable<global::System.Boolean> _OFFUPDT;
        partial void OnOFFUPDTChanging(Nullable<global::System.Boolean> value);
        partial void OnOFFUPDTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> NKKCODE
        {
            get
            {
                return _NKKCODE;
            }
            set
            {
                OnNKKCODEChanging(value);
                ReportPropertyChanging("NKKCODE");
                _NKKCODE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NKKCODE");
                OnNKKCODEChanged();
            }
        }
        private Nullable<global::System.Decimal> _NKKCODE;
        partial void OnNKKCODEChanging(Nullable<global::System.Decimal> value);
        partial void OnNKKCODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BKDT
        {
            get
            {
                return _BKDT;
            }
            set
            {
                OnBKDTChanging(value);
                ReportPropertyChanging("BKDT");
                _BKDT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BKDT");
                OnBKDTChanged();
            }
        }
        private Nullable<global::System.DateTime> _BKDT;
        partial void OnBKDTChanging(Nullable<global::System.DateTime> value);
        partial void OnBKDTChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PMSDataModel", "FK_PMSITEM_MAINITEM", "MAINITEM")]
        public MAINITEM MAINITEM
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MAINITEM>("PMSDataModel.FK_PMSITEM_MAINITEM", "MAINITEM").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MAINITEM>("PMSDataModel.FK_PMSITEM_MAINITEM", "MAINITEM").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MAINITEM> MAINITEMReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MAINITEM>("PMSDataModel.FK_PMSITEM_MAINITEM", "MAINITEM");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MAINITEM>("PMSDataModel.FK_PMSITEM_MAINITEM", "MAINITEM", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
